[General]
showlogo=shown
showClock=true
logo=/usr/share/icons/neebles-theme/neebles-launcher.png
type=image
color=#7C3AED
fontSize=10
background=/usr/share/wallpapers/neebles-theme/contents/images/1920x1080.png
