dontChroot: false
timeout: 60
script:
  - "rm -f /usr/sbin/policy-rc.d"
  - "rm -f /etc/debian_chroot"
  - "rm -rf /etc/live"
  - "rm -rf /opt/neebles-build/calamares"
  - "rm -f /usr/bin/neebles-installer"
  - "rm -f /usr/bin/calamares-install-debian"
  - "rm -f /usr/bin/add-calamares-desktop-icon"
  - "rm -f /usr/share/applications/neebles-installer.desktop"
  - "rm -f /usr/share/applications/calamares-install-debian.desktop"
  - "rm -f /usr/share/polkit-1/actions/org.neebles.calamares.policy"
  - "ssh-keygen -A"
